### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by ThiagoCM** [mcdeoliveira/pyctrl#4]
Hi guys,

I'm currently reading and running each example on the User Guide, in order to understand better the library. I've faced an error related to the Closed-Loop Control. 

The error is shown below:

>Traceback (most recent call last):
>  File ".\file.py", line 1, in <module>
>   from pyctrl.rc import Controller
>  File "...\Programs\Python\Python36-32\lib\site-packages\pyctrl\rc\__init__.py", line 3, in <module>
>    import rcpy
>ModuleNotFoundError: No module named 'rcpy'

I've tried to install rcpy via pip3, but I've had no success so far. I didn't find any resourceful material related to installing errors on the rcpy package. Any  tips?

Thanks in advance.

**Comment by mcdeoliveira** [comment]
Please visit https://github.com/mcdeoliveira/rcpy for instructions on how to install that library. You will need to have access to a Beaglebone Black + Robotics Cape or Beaglebone Blue to run it though.
